'use client';
/* oxlint-disable next/no-img-element -- Images use responsive CSS and direct Shopify CDN sizing; no image optimiser is deployed. */
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {Search,ShoppingBag,Menu,ChevronDown,ArrowRight,ArrowLeft,Plus,Minus,MessageCircle} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import catalog from './catalog.json';
import {shopConfig} from './shop-config';
import StoreImage from './store-image';
type Product=typeof catalog[number];
type Item={id:string;color:string;qty:number};
const img=(s:string)=>'/images/'+s;
const assets={hero:img('kings-table-hero.png'),flatware:img('YD_082626_5050_Flatware_v01_a2732651-fd90-4413-a108-783da09422e6.jpg'),ceramic:img('YD_051526_CeramicCore_v2.jpg'),bundle:img('YD_052626_Bundle-main_v01.jpg'),splatter:img('YD_052626_MediaText-1_v01.jpg'),palm:img('YD_052626_MediaText-2_v01.jpg')};
const categories=['Bundles','Ceramics','Flatware','Outdoor','Linens','Kitchen','Glass'];
const slug=(s:string)=>s.toLowerCase().replaceAll(' & ','-').replaceAll(' ','-');
const categoryUrl=(s:string)=>'/collections/'+(s==='Shop All'?'all':s==='Bundles'?'bundle-sets':slug(s));
const colors:Record<string,string>={Moon:'#f5f3ed',Palm:'#c2c1a0',Plum:'#573647',Balsam:'#485949',Midnight:'#3c465c',Fog:'#b3b4b4',Canyon:'#ba7655',Daybreak:'#e8c4b7',Dune:'#cfb8a0','Matte Gold':'#b89c5d','Vintage Gold':'#a58d51','Matte Black':'#292a2b','Polished Steel':'#c5c6c7','Matte Steel':'#acadaf',Clear:'#e1ebed'};
function collectionProducts(key:string){const q=key.toLowerCase();if(['all','new-arrivals','best-sellers','sale'].includes(q))return catalog;if(q==='bundle-sets'||q.includes('bundle'))return catalog.filter(p=>/bundle|core set|stocked|serving set|yes chef|bowl over/i.test(p.type+' '+p.name));if(q==='ceramics')return catalog.filter(p=>/ceramic/i.test(p.type)||/plate|bowl|mug/i.test(p.name)&&!/outdoor|mixing/i.test(p.name));if(q==='kitchen')return catalog.filter(p=>/kitchen|bakeware|accessories/i.test(p.type)||/crock|cellar|rest|trivet|baker|mixing|dip dish/i.test(p.name));return catalog.filter(p=>(p.type+' '+p.name+' '+p.tags.join(' ')).toLowerCase().includes(q.replace('-collection','').replaceAll('-',' ')));}
const best=['the-core-set','glossy-big-bowls','flatware-setting','glossy-ig-plates'].map(id=>catalog.find(p=>p.id===id)).filter(Boolean) as Product[];
function photo(p:Product,color:string){return p.variants.find(v=>v.color===color)?.image||p.images[0]}
function Swatches({p,value,onChange}:{p:Product;value:string;onChange:(v:string)=>void}){return <div className="swatches" aria-label="Choose colour">{p.colors.filter(c=>c!=='Default Title').map(c=><button key={c} aria-label={c} aria-pressed={value===c} title={c} onClick={()=>onChange(c)} className={value===c?'selected':''} style={{background:colors[c]||'#ddd5c9'}}/>)}</div>}
function Card({p,add}:{p:Product;add:(p:Product,c:string)=>void}){const [color,setColor]=useState(p.colors[0]||'');return <article className="product-card"><Link href={'/products/'+p.id} className="product-image"><StoreImage src={photo(p,color)} alt={p.name+' in '+color} loading="lazy"/>{p.images[1]&&<StoreImage className="hover-image" src={p.images[1]} alt="" loading="lazy"/>}</Link><div className="card-top"><Link href={'/products/'+p.id}>{p.name}</Link><span>Price on request</span></div><Swatches p={p} value={color} onChange={setColor}/><div className="card-bottom"><span>{color==='Default Title'?'':color}</span><button onClick={()=>add(p,color)} aria-label={'Add '+p.name+' to cart'}>Add to cart <Plus size={15}/></button></div></article>}
function Grid({items,add}:{items:Product[];add:(p:Product,c:string)=>void}){return <div className="product-grid">{items.map(p=><Card key={p.id} p={p} add={add}/>)}</div>}
export default function Storefront({path}:{path:string}){
const [cart,setCart]=useState<Item[]>([]),[ready,setReady]=useState(false),[drawer,setDrawer]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[menu,setMenu]=useState(''),[mobile,setMobile]=useState(false),[order,setOrder]=useState(false),[notice,setNotice]=useState('');
// Hydrate the browser-owned cart after SSR.
// oxlint-disable-next-line react/react-compiler
useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('kings-cart')||'[]');setCart(saved.filter((i:Item)=>catalog.some(p=>p.id===i.id)&&Number.isInteger(i.qty)&&i.qty>0));}catch{}setReady(true)},[]);
useEffect(()=>{if(ready)localStorage.setItem('kings-cart',JSON.stringify(cart))},[cart,ready]);

const add=(p:Product,color:string,qty=1)=>{setCart(old=>{const existing=old.find(i=>i.id===p.id&&i.color===color);return existing?old.map(i=>i===existing?{...i,qty:i.qty+qty}:i):[...old,{id:p.id,color,qty}]});setDrawer(true)};
const update=(idx:number,delta:number)=>setCart(c=>c.map((i,n)=>n===idx?{...i,qty:i.qty+delta}:i).filter(i=>i.qty>0));
const count=cart.reduce((n,i)=>n+i.qty,0);
const orderNow=()=>{setDrawer(false);setOrder(true);setNotice('')};
const submitOrder=(e:React.SyntheticEvent<HTMLFormElement>)=>{e.preventDefault();if(!shopConfig.whatsappNumber){setNotice('WhatsApp ordering will be available soon. Your selection is saved in your cart.');return;}const f=new FormData(e.currentTarget);const field=(name:string)=>{const value=f.get(name);return typeof value==='string'?value:''};const message=['Hello Kings Crockery! I would like to order:',...cart.map(i=>`${catalog.find(p=>p.id===i.id)?.name} — ${i.color} × ${i.qty}`),`Name: ${field('name')}`,`Phone: ${field('phone')}`,`Delivery address: ${field('address')}`,`Please confirm availability, the total price and payment instructions for the Rs 250 advance.`].join('\n');window.location.href=`https://wa.me/${shopConfig.whatsappNumber}?text=${encodeURIComponent(message)}`};
const mainKey=path.split('/').pop()||'';
const p=catalog.find(p=>p.id===mainKey);
return <><a className="skip-link" href="#main">Skip to content</a><div className="announcement">{shopConfig.policy}</div><header className="site-header" onMouseLeave={()=>setMenu('')}><div className="header-main"><div className="header-left"><button className="mobile-menu icon-button" aria-label="Open menu" onClick={()=>setMobile(true)}><Menu/></button><button className="icon-button" aria-label="Search products" onClick={()=>setSearch(true)}><Search/></button></div><Link className="wordmark" href="/">KINGS CROCKERY</Link><button className="cart-button" aria-label={`Open cart, ${count} items`} onClick={()=>setDrawer(true)}><ShoppingBag size={23}/><span>{count}</span></button></div><nav className="desktop-nav">{['Shop',...categories,'About'].map(n=><button key={n} aria-expanded={menu===n} onMouseEnter={()=>setMenu(n)} onClick={()=>setMenu(menu===n?'':n)}>{n}<ChevronDown size={13}/></button>)}</nav>{menu&&<div className="mega-menu"><div><h3>{menu==='About'?'About Kings Crockery':'Shop by Category'}</h3>{(menu==='About'?['Our Story','Craftsmanship','Care Guide','Our Hours Blog']:['Shop All',...categories,'Serving Pieces','Bakeware']).map(n=><Link key={n} href={menu==='About'?'/pages/'+slug(n):categoryUrl(n)}>{n}</Link>)}</div><div><h3>{menu==='About'?'Customer Service':'Discover the Collection'}</h3>{(menu==='About'?['Contact','FAQ','Shipping & Returns']:['New Arrivals','Best Sellers','Glossy Collection','Splatter Collection','Plates','Bowls','Mugs']).map(n=><Link key={n} href={menu==='About'?'/pages/'+slug(n):categoryUrl(n)}>{n}</Link>)}<Link href="/pages/build-your-bundle">Build Your Own Bundle</Link></div><Link className="menu-feature" href={categoryUrl(menu==='Shop'?'Ceramics':menu==='About'?'Bundles':menu)}><StoreImage src={menu==='Flatware'?assets.flatware:assets.ceramic} alt="Beautifully set table"/><span>Made for your everyday table <ArrowRight size={18}/></span></Link></div>}</header>
<main id="main">{path==='/'?<><section className="hero"><StoreImage className="hero-photo" src={assets.hero} alt="A beautifully set table" loading="eager"/><div className="hero-copy"><p>Make every gathering a little more special</p><h1>A Beautiful Table.<br className="mobile-only"/> Every Day.</h1><Link className="button white" href="/collections/all">Shop the collection</Link></div><div className="advance-seal">RS 250<span>ADVANCE<br/>TO CONFIRM</span></div></section><div className="marquee" aria-label="Thoughtfully chosen for your table"><div>{Array.from({length:6},(_,i)=><span key={i}>YOUR TABLE, YOUR WAY <span className="star">✳</span> KINGS CROCKERY <span className="star">✳</span></span>)}</div></div><section className="section"><h2>Best Sellers</h2><Grid items={best} add={add}/></section><section className="split"><StoreImage src={assets.flatware} alt="Flatware arranged for a gathering" loading="lazy"/><div><h2>A Little Polish.<br/>A Lot of Possibility.</h2><p>The finishing touch for everything from a quiet breakfast to a table full of friends.</p><Link className="button" href="/collections/flatware">Shop flatware</Link></div></section><section className="split reverse"><StoreImage src={assets.ceramic} alt="A ceramic dinnerware setting" loading="lazy"/><div><h2>Your Everyday<br/>Favourites, Together.</h2><p>Find the shapes and colours that make your table feel like home. Start with a set, then make it your own.</p><Link className="button" href="/collections/bundle-sets">Shop core sets</Link></div></section><section className="bundle-section"><div className="bundle-heading"><h2>Better Together</h2><p>A place for everything. A setting for everyone.</p><Link className="text-link" href="/collections/bundle-sets">Shop bundles <ArrowRight size={18}/></Link></div><div className="bundle-layout"><StoreImage src={assets.bundle} alt="Coordinated tableware" loading="lazy"/><Grid items={collectionProducts('bundle-sets').slice(0,4)} add={add}/></div></section><section className="editorial-pair">{[['A Playful Little Splatter',assets.splatter,'splatter-collection'],['Meet Your Calmer Side',assets.palm,'ceramics']].map(([title,url,to])=><Link key={to} href={'/collections/'+to}><StoreImage src={url} alt={title} loading="lazy"/><div><h2>{title}</h2><span className="button white">Explore the collection</span></div></Link>)}</section><CategoryStrip/></>:path.includes('/products/')?(p?<ProductPage key={p.id} p={p} add={add} orderNow={(color,qty)=>{add(p,color,qty);setDrawer(false);setOrder(true)}}/>:<Missing/>):path.includes('/collections/')?<Collection key={mainKey} collection={mainKey} add={add}/>:path==='/cart'?<section className="section cart-page"><h1>Your Shopping Cart</h1>{renderCart()}<button className="button" disabled={!count} onClick={orderNow}>Order Now on WhatsApp</button></section>:mainKey==='build-your-bundle'?<BundleBuilder add={add}/>:<InfoPage page={mainKey} orderNow={orderNow}/>}</main>
<footer><div className="footer-top"><div className="footer-brand"><Link href="/" className="wordmark">KINGS<br/>CROCKERY</Link><p>A beautiful table.<br/>Every day.</p></div><div><h3>Shop</h3>{['Shop All','New Arrivals','Best Sellers',...categories].map(n=><Link key={n} href={categoryUrl(n)}>{n}</Link>)}</div><div><h3>Customer Service</h3>{['Contact','FAQ','Shipping & Returns','Order Policy','Privacy Policy','Terms of Use','Accessibility'].map(n=><Link key={n} href={'/pages/'+slug(n)}>{n==='FAQ'?'Help & FAQ':n}</Link>)}</div><div><h3>About</h3>{['Our Story','Our Hours Blog','Craftsmanship','Care Guide'].map(n=><Link key={n} href={'/pages/'+slug(n)}>{n}</Link>)}<button className="footer-order" onClick={orderNow}><MessageCircle size={18}/> Order Now</button></div></div><div className="footer-policy">{shopConfig.policy}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} Kings Crockery</span><span>Pakistan · PKR</span><a href="#main">Back to top ↑</a></div></footer>
<Sheet open={drawer} onOpenChange={setDrawer}><SheetContent className="store-sheet"><SheetTitle>Your Cart ({count})</SheetTitle><SheetDescription>Choose your favourites, then confirm your order on WhatsApp.</SheetDescription>{renderCart()}{count>0&&<div className="cart-checkout"><p className="total-line"><span>Order total</span><span>Confirmed on WhatsApp</span></p><p className="advance-note">{shopConfig.policy}</p><button className="button" onClick={orderNow}>Order Now <MessageCircle size={19}/></button><Link href="/cart" className="text-link" onClick={()=>setDrawer(false)}>View cart</Link></div>}</SheetContent></Sheet>
<Sheet open={search} onOpenChange={setSearch}><SheetContent side="top" className="search-sheet"><SheetTitle>Find your everyday favourites</SheetTitle><SheetDescription>Search by product, colour or collection.</SheetDescription><label className="search-input"><Search/><input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search plates, bowls, mugs…"/></label><div className="search-results">{(query?catalog.filter(p=>(p.name+' '+p.type+' '+p.colors.join(' ')).toLowerCase().includes(query.toLowerCase())):best).slice(0,8).map(p=><Link onClick={()=>setSearch(false)} key={p.id} href={'/products/'+p.id}><StoreImage src={p.images[0]} alt=""/><span>{p.name}<small>{p.type}</small></span><ArrowRight size={18}/></Link>)}{query&&!catalog.some(p=>(p.name+' '+p.type+' '+p.colors.join(' ')).toLowerCase().includes(query.toLowerCase()))&&<p>No products found. Try “plates” or “bowls”.</p>}</div></SheetContent></Sheet>
<Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="store-sheet"><SheetTitle>Kings Crockery</SheetTitle><SheetDescription>Find something lovely for your table.</SheetDescription>{['Shop All',...categories].map(n=><Link className="mobile-nav-link" onClick={()=>setMobile(false)} href={categoryUrl(n)} key={n}>{n}<ArrowRight size={18}/></Link>)}<Link href="/pages/our-story" onClick={()=>setMobile(false)}>Our Story</Link></SheetContent></Sheet>
<Sheet open={order} onOpenChange={setOrder}><SheetContent className="store-sheet"><SheetTitle>Order on WhatsApp</SheetTitle><SheetDescription>Share your selection and delivery details with Kings Crockery.</SheetDescription><p className="advance-note">{shopConfig.policy} Payment details and the full order amount will be confirmed on WhatsApp.</p>{!shopConfig.whatsappNumber&&<p className="setup-notice">WhatsApp ordering is coming soon. You can still browse and save items to your cart.</p>}<form onSubmit={submitOrder} className="order-form"><label>Your name<input required name="name" autoComplete="name"/></label><label>Phone number<input required name="phone" type="tel" autoComplete="tel"/></label><label>Delivery address<textarea required name="address" autoComplete="street-address" rows={3}/></label><p>{count} item{count===1?'':'s'} in your order. No payment is taken on this website.</p><button className="button" type="submit">Continue to WhatsApp <MessageCircle size={18}/></button><output>{notice}</output></form></SheetContent></Sheet></>;
function renderCart(){return <div className="cart-items">{!count?<div className="empty-cart"><ShoppingBag size={42}/><h2>A table waiting to happen.</h2><p>Your cart is currently empty.</p><Link onClick={()=>setDrawer(false)} className="button" href="/collections/all">Explore the collection</Link></div>:cart.map((i,idx)=>{const p=catalog.find(p=>p.id===i.id)!;return <div className="cart-item" key={i.id+i.color}><StoreImage src={photo(p,i.color)} alt={p.name}/><div><Link href={'/products/'+p.id} onClick={()=>setDrawer(false)}>{p.name}</Link><p>{i.color==='Default Title'?'':i.color}</p><div className="quantity"><button aria-label={'Decrease '+p.name+' quantity'} onClick={()=>update(idx,-1)}><Minus size={14}/></button><span>{i.qty}</span><button aria-label={'Increase '+p.name+' quantity'} onClick={()=>update(idx,1)}><Plus size={14}/></button></div><button className="remove" onClick={()=>setCart(c=>c.filter((_,n)=>n!==idx))}>Remove</button></div></div>})}</div>}
}
function CategoryStrip(){const scroll=useRef<HTMLDivElement>(null);const pics=[img('YD_052626_CategoryBlock-Bundles_v01.jpg'),img('yd-dune.jpg'),img('Flatware_mobile.jpg'),img('outdoorlp_blockv3.jpg'),img('YD_linens.jpg'),img('YD_052626_CategoryBlock-Kitchen_v01.jpg'),img('yearandday_glass_tray2.jpg')];return <section className="section categories"><div className="section-heading"><h2>Shop by Category</h2><div><button aria-label="Previous categories" onClick={()=>scroll.current?.scrollBy({left:-500,behavior:'smooth'})}><ArrowLeft/></button><button aria-label="Next categories" onClick={()=>scroll.current?.scrollBy({left:500,behavior:'smooth'})}><ArrowRight/></button></div></div><div className="category-strip" ref={scroll}>{categories.map((n,i)=><Link key={n} href={categoryUrl(n)}><StoreImage src={pics[i]} alt={n} loading="lazy"/><h3>{n}</h3></Link>)}</div></section>}
function Collection({collection,add}:{collection:string;add:(p:Product,c:string)=>void}){const [sort,setSort]=useState('Featured'),[color,setColor]=useState('All colours'),[limit,setLimit]=useState(24);const list=collectionProducts(collection).filter(p=>color==='All colours'||p.colors.includes(color));const sorted=sort==='Name A–Z'?[...list].sort((a,b)=>a.name.localeCompare(b.name)):sort==='Name Z–A'?[...list].sort((a,b)=>b.name.localeCompare(a.name)):list;const title=collection==='all'?'Shop All':collection==='bundle-sets'?'Bundles':collection.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join(' ');return <><div className="collection-heading"><p className="eyebrow">Kings Crockery / The collection</p><h1>{title}</h1><p>Beautiful pieces for the everyday and the occasions in between.</p></div><div className="collection-tabs">{['Shop All',...categories].map(n=><Link className={categoryUrl(n).endsWith('/'+collection)?'active':''} key={n} href={categoryUrl(n)}>{n}</Link>)}</div><section className="section collection"><div className="filter-bar"><span>{list.length} products</span><div><Select value={color} onValueChange={v=>{setColor(v||'All colours');setLimit(24)}}><SelectTrigger aria-label="Filter by colour"><SelectValue/></SelectTrigger><SelectContent>{['All colours',...new Set(collectionProducts(collection).flatMap(p=>p.colors))].filter(c=>c!=='Default Title').map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={v=>setSort(v||'Featured')}><SelectTrigger aria-label="Sort products"><SelectValue/></SelectTrigger><SelectContent>{['Featured','Name A–Z','Name Z–A'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div></div><Grid items={sorted.slice(0,limit)} add={add}/>{!list.length&&<div className="empty-cart"><h2>This collection is taking shape.</h2><Link href="/collections/all" className="button">Shop all pieces</Link></div>}{limit<list.length&&<button className="button load-more" onClick={()=>setLimit(v=>v+24)}>Load more ({list.length-limit} remaining)</button>}</section></>}
function ProductPage({p,add,orderNow}:{p:Product;add:(p:Product,c:string,q?:number)=>void;orderNow:(c:string,q:number)=>void}){const[color,setColor]=useState(p.colors[0]||''),[qty,setQty]=useState(1),[active,setActive]=useState('');return <><div className="breadcrumb"><Link href="/collections/all">Shop</Link> / <Link href={categoryUrl(p.type)}>{p.type}</Link> / {p.name}</div><section className="product-detail"><div className="gallery"><StoreImage className="main-product" src={active||photo(p,color)} alt={p.name+' '+color}/><div className="thumbnails">{p.images.map((url,i)=><button key={url} onClick={()=>setActive(url)} aria-label={'View product photo '+(i+1)}><StoreImage src={url} alt={p.name+' detail '+(i+1)}/></button>)}</div></div><div className="product-info"><p className="eyebrow">Kings Crockery · {p.type}</p><h1>{p.name}</h1><p className="product-price">Price confirmed on WhatsApp</p><p>Bring your own style to the table. Choose your favourite finish and add this piece to your collection.</p><div className="product-options"><p>Colour: <strong>{color==='Default Title'?'Standard':color}</strong></p><Swatches p={p} value={color} onChange={v=>{setColor(v);setActive('')}}/></div><div className="buy-row"><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))} aria-label="Decrease quantity"><Minus size={16}/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)} aria-label="Increase quantity"><Plus size={16}/></button></div><button className="button" onClick={()=>add(p,color,qty)}>Add to cart</button></div><button className="button outline order-product" onClick={()=>orderNow(color,qty)}>Order Now <MessageCircle size={18}/></button><p className="advance-note">{shopConfig.policy}</p><details open><summary>Product details <Plus size={16}/></summary><p>{p.name}. Select the finish shown above. Please confirm current stock, set contents, dimensions and pricing with us before payment.</p></details><details><summary>Care guide <Plus size={16}/></summary><p>Handle with care. Use a soft sponge and mild detergent. Confirm whether this particular item is dishwasher, oven or microwave safe before use.</p><Link className="text-link" href="/pages/care-guide">Read the care guide</Link></details><details><summary>Delivery & ordering <Plus size={16}/></summary><p>Send your cart and address through WhatsApp. Pay the Rs 250 advance using the payment details we provide. Your order is dispatched after payment confirmation.</p></details></div></section><section className="section"><h2>Complete Your Table</h2><Grid items={catalog.filter(v=>v.type===p.type&&v.id!==p.id).slice(0,4)} add={add}/></section></>}
function BundleBuilder({add}:{add:(p:Product,c:string)=>void}){return <><div className="collection-heading"><p className="eyebrow">Make it your own</p><h1>Build Your Own Bundle</h1><p>Mix colours, shapes and finishes. Add your pieces, then review your selection in the cart.</p></div><section className="section"><Grid items={catalog.filter(p=>/plate|bowl|mug/i.test(p.name)&&!/set|outdoor/i.test(p.name)).slice(0,24)} add={add}/></section></>}
function Missing(){return <div className="empty-cart"><h1>We couldn’t find that page.</h1><Link className="button" href="/collections/all">Explore the collection</Link></div>}
function InfoPage({page,orderNow}:{page:string;orderNow:()=>void}){const title=page.split('-').map(s=>s[0]?.toUpperCase()+s.slice(1)).join(' ');if(['our-story','craftsmanship'].includes(page))return <><section className="story-hero"><StoreImage src={assets.ceramic} alt="A thoughtfully set table"/><div><p className="eyebrow">Kings Crockery</p><h1>{page==='our-story'?'Good Days Begin Around a Table.':'The Details Make the Difference.'}</h1><p>From everyday meals to your most memorable gatherings, the pieces on your table become part of the moment.</p></div></section><section className="prose"><h2>A place at your table.</h2><p>Kings Crockery brings together pieces for the way you eat, gather and celebrate. Explore ceramics, flatware, glass and finishing touches, and put together a setting that feels like you.</p><p>For product materials, dimensions and availability, speak with us before ordering. We’ll help you find the right pieces for your home.</p><Link className="button" href="/collections/all">Find your favourites</Link></section></>;if(page==='our-hours-blog')return <><div className="collection-heading"><p className="eyebrow">At the Kings Crockery table</p><h1>Our Hours</h1><p>Ideas for the moments you make at home.</p></div><div className="journal-grid">{[['setting-the-everyday-table','Setting the Everyday Table',assets.ceramic],['mixing-your-colours','A Table in Your Colours',assets.palm],['caring-for-your-crockery','Care for the Pieces You Love',assets.flatware]].map(([s,t,i])=><Link href={'/pages/'+s} key={s}><StoreImage src={i} alt={t}/><h2>{t}</h2><span className="text-link">Read the story <ArrowRight size={17}/></span></Link>)}</div></>;
const faqs=[['How do I place an order?','Add your chosen items to the cart, select Order Now, and share your delivery details through WhatsApp. We will confirm stock, the full price and payment instructions.'],['What is the Rs 250 advance?','A Rs 250 advance payment is required to confirm every order. We dispatch your order to your provided address after confirming receipt of the payment.'],['How do I pay?','Payment instructions are provided on WhatsApp when your order is confirmed. This website does not collect payment details or process payments.'],['When will my order arrive?','The dispatch schedule, delivery estimate and any delivery charges will be confirmed on WhatsApp before you pay.'],['Can I change my order or return an item?','Contact us through WhatsApp with your order details. Confirm the applicable cancellation and return terms with us before paying.']];
const care=[['Ceramics','Wash gently with a soft sponge and mild detergent. Avoid sudden temperature changes and check the specific item’s care instructions before using a dishwasher, oven or microwave.'],['Flatware','Rinse after use and dry with a soft cloth. Avoid abrasive cleaners, especially on coloured finishes.'],['Glass','Handle carefully, wash with a non-abrasive sponge and avoid thermal shocks.'],['Linens','Check the care label for washing and ironing temperatures. Wash similar colours together.']];
return <section className="info-page"><p className="eyebrow">Kings Crockery</p><h1>{page==='faq'?'How Can We Help?':title}</h1>{['faq','shipping-returns','order-policy'].includes(page)?<div className="faq-list">{faqs.map(([q,a])=><details key={q} open={page!=='faq'}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div>:page==='care-guide'||page==='caring-for-your-crockery'?<div className="faq-list">{care.map(([q,a])=><details key={q} open><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div>:page==='contact'?<><p>Need help choosing a piece or placing an order? Share your selection with us on WhatsApp.</p><button className="button" onClick={orderNow}>Contact on WhatsApp <MessageCircle size={18}/></button><p className="advance-note">{shopConfig.policy}</p></>:page==='privacy-policy'?<><p>Your cart is saved in this browser so you can return to your selection. Delivery details entered in the order form are included in a WhatsApp message only when you continue to WhatsApp.</p><p>This website does not collect payment card details. WhatsApp processes information under its own privacy policy. Contact Kings Crockery about information shared when placing an order.</p></>:page==='terms-of-use'?<><p>Product availability, specifications, prices and delivery terms must be confirmed with Kings Crockery through WhatsApp before payment. A cart selection is an order enquiry until accepted by Kings Crockery.</p><p>{shopConfig.policy}</p></>:page==='accessibility'?<p>You can navigate this store using your keyboard, browse at larger text sizes, and use reduced-motion settings. If you need help with an order, contact us through WhatsApp.</p>:page==='setting-the-everyday-table'?<><StoreImage className="article-image" src={assets.ceramic} alt="Ceramic table setting"/><p>Start with a dinner plate and a bowl, then add a glass and the cutlery your meal needs. Leave room between settings and bring serving pieces into the centre so everyone can share.</p><p>A simple linen and a single colour can make an everyday meal feel considered. Let the food and the company do the rest.</p></>:page==='mixing-your-colours'?<><StoreImage className="article-image" src={assets.palm} alt="Mixing tableware colours"/><p>Choose one colour as your starting point. Add a softer shade for contrast, or repeat the same finish for an understated setting. A neutral tablecloth gives each piece space to stand out.</p></>:<Missing/>}</section>}


